# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true
