name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_toolchain_x86_64:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt-get install build-essential libtool-bin linux-headers-$(uname -r) help2man

    - name: Build toolchain
      run: CICD=true python3 -m mayflower toolchain build --arch=x86_64

    - name: Linux Logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: x86-64-linux-gnu-toolchain-logs
        path: mayflower/_toolchain/build.log
        retention-days: 5

    - name: Create Tarball
      run: tar -C mayflower/_toolchain -cJf toolchain-x86_64-linux-gnu.tar.xz  x86_64-linux-gnu

    - name: Toolchain build
      uses: actions/upload-artifact@v3
      with:
        name: toolchain-x86_64-linux-gnu.tar.xz
        path: toolchain-x86_64-linux-gnu.tar.xz
        retention-days: 5

  build_toolchain_aarch64:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt-get install build-essential libtool-bin linux-headers-$(uname -r) help2man

    - name: Build toolchain
      run: CICD=true python3 -m mayflower toolchain build --arch=aarch64

    - name: Linux Logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: aarch64-linux-gnu-toolchain-logs
        path: mayflower/_toolchain/build.log
        retention-days: 5

    - name: Create Tarball
      run: tar -C mayflower/_toolchain -cJf toolchain-aarch64-linux-gnu.tar.xz  aarch64-linux-gnu

    - name: Toolchain build
      uses: actions/upload-artifact@v3
      with:
        name: toolchain-aarch64-linux-gnu.tar.xz
        path: toolchain-aarch64-linux-gnu.tar.xz
        retention-days: 5

  build_linux_x86_64:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt-get install build-essential bison linux-headers-$(uname -r)

    - name: fetch toolchain
      run: CICD=true python3 -m mayflower toolchain download --arch=x86_64

    - name: build
      run: CICD=true python3 -m mayflower build --arch=x86_64

    - name: Linux Logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: x86-64-linux-gnu-logs
        path: mayflower/_logs/*
        retention-days: 5

    - name: Create Tarball
      run: tar -C mayflower/_build -cJf python-x86_64-linux-gnu.tar.xz  x86_64-linux-gnu

    - name: Python build
      uses: actions/upload-artifact@v3
      with:
        name: python-x86_64-linux-gnu.tar.xz
        path: python-x86_64-linux-gnu.tar.xz
        retention-days: 5

  build_linux_aarch64:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt-get install build-essential bison linux-headers-$(uname -r)

    - name: fetch toolchain
      run: CICD=true python3 -m mayflower toolchain download --arch=aarch64

    - name: fetch native build
      run: CICD=true python3 -m mayflower fetch

    - name: build
      run: CICD=true python3 -m mayflower build --arch=aarch64

    - name: Linux Logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: aarch64-linux-gnu-logs
        path: mayflower/_logs/*
        retention-days: 5

    - name: Create Tarball
      run: tar -C mayflower/_build -cJf python-aarch64-linux-gnu.tar.xz  aarch64-linux-gnu

    - name: Python build
      uses: actions/upload-artifact@v3
      with:
        name: python-aarch64-linux-gnu.tar.xz
        path: python-aarch64-linux-gnu.tar.xz
        retention-days: 5

  build_osx_x86_64:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: CICD=true python3 -m mayflower.build.darwin

    - name: MacOS Logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: x86_64-macos-logs
        path: mayflower/_logs/*
        retention-days: 5

    - name: Create Tarball
      run: tar -C mayflower/_build -cJf python-x86_64-macos.tar.xz x86_64-macos

    - name: Python build
      uses: actions/upload-artifact@v3
      with:
        name: python-x86_64-macos.tar.xz
        path: python-x86_64-macos.tar.xz
        retention-days: 5

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create virtualenv
      run: python3 -m venv venv && source venv/bin/activate

    - name: Install python dependencies
      run: pip3 install pytest


    - name: Run tests
      run: pytest -v tests/
