name: Build

on:
  workflow_call:
    inputs:
      changed-files:
        type: string
        description: Build relenv python builds

jobs:

  build_linux:

    strategy:
      fail-fast: false
      matrix:
        version:
          - 3.10.15
          - 3.11.10
          - 3.12.7
          - 3.13.0
        host:
          - x86_64
        include:
          - host: x86_64
            target: x86_64

    name: "Python ${{ matrix.version }}  Linux ${{ matrix.target }} on ${{ matrix.host }}"

    runs-on:
      - ${{ (contains(matrix.host, 'x86_64') && 'linux-x86_64') || 'linux-arm64' }}

    env:
      RELENV_DATA: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bison python3-all patchelf swig cmake libldap2-dev libsasl2-dev ldap-utils libssl-dev pkg-config libvirt-dev default-libmysqlclient-dev python3-virtualenv
          virtualenv venv
          venv/bin/pip3 install nox

      - name: Python Version
        run: |
          venv/bin/python3 --version
          venv/bin/python3 -c 'import os; print(os.name)'

      - name: Download Toolchain Artifact
        uses: actions/download-artifact@v4
        with:
          name: toolchain-${{ matrix.host }}-${{ matrix.target }}-linux-gnu.tar.xz
          path: .

      - name: Extract Toolchain Artifact
        run: |
          mkdir -p toolchain
          tar -C toolchain -xvf toolchain-${{ matrix.host }}-${{ matrix.target }}-linux-gnu.tar.xz

      - name: Build
        run: |
          venv/bin/python3 -m relenv build --arch=${{ matrix.target }} --python=${{ matrix.version }}

     # - name: Verify Build
     #   if: ${{ matrix.host == matrix.target }}
     #   run: |
     #     venv/bin/python3 -m nox -e tests -- -s tests/test_verify_build.py

      - name: Linux Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.version }}-${{ matrix.host }}-${{ matrix.target }}-linux-gnu-logs
          path: logs/*
          retention-days: 5

      - name: "Upload artifact: build/${{ matrix.version }}-${{ matrix.target }}-linux-gnu.tar.xz"
        uses: actions/upload-artifact@v4
        if: ${{ matrix.host == matrix.target  && always()}}
        with:
          name: ${{ matrix.version }}-${{ matrix.target }}-linux-gnu.tar.xz
          path: build/${{ matrix.version }}-${{ matrix.target }}-linux-gnu.tar.xz
          retention-days: 5
