name: CI

concurrency:
  # Concurrency is defined in a way that concurrent builds against branches do
  # not cancel previous builds.
  # However, for every new build against the same pull request source branch,
  # all older builds against that same branch get canceled.
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.repository }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      kind:
        required: false
        type: string
        default: dev
      package_command:
        required: false
        type: string
        description: Command used to build python package
        default: >-
          python -m
          build
          -C--global-option=egg_info
          -C--global-option=--tag-build=+dev$(git rev-parse --short HEAD)
          --wheel
          --outdir dist/

jobs:

  get-changed-files:
    name: Get Changed Files
    runs-on: ubuntu-latest
    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files
      pull-requests: read  # for dorny/paths-filter to read pull requests
    outputs:
      changed-files: ${{ toJSON(steps.changed-files.outputs) }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Changed Files
        id: changed-files
        uses: dorny/paths-filter@v2
        with:
          token: ${{ github.token }}
          list-files: json
          filters: |
            repo:
              - added|modified:
                - '**'
            deleted:
              - deleted:
                - '**'
            toolchain:
              - added|modified:
                - '.github/workflows/*toolchain*.yml'
                - 'relenv/toolchain.py'
                - 'relenv/_toolchain/**'

  build-python-package:
    name: Python Package
    uses: ./.github/workflows/package-action.yml
    if: always()
    with:
    with:
      kind: "${{ inputs.kind }}"
      cmd: "${{ inputs.package_command }}"

  toolchain:
    name: Toolchain Builds
    uses: ./.github/workflows/toolchain-action.yml
    needs:
      - get-changed-files
    with:
      changed-files: ${{ needs.get-changed-files.outputs.changed-files }}

  build-native:
    name: Python Native Builds
    uses: ./.github/workflows/build-native-action.yml
    needs:
      - get-changed-files
      - toolchain
    with:
      changed-files: ${{ needs.get-changed-files.outputs.changed-files }}

