name: Docs

on: [push, pull_request]

permissions:
  contents: read

jobs:
  mayflower-docs:
    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files
      pull-requests: read  # for dorny/paths-filter to read pull requests
    name: Build Mayflower Documentation
    runs-on: ubuntu-latest

    container:
      image: python:3.8.6-slim-buster

    steps:
      - name: Install System Deps
        run: |
          echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list
          apt-get update
          apt-get install -y enchant git gcc imagemagick make zlib1g-dev libc-dev libffi-dev g++ libxml2 libxml2-dev libxslt-dev libcurl4-openssl-dev libssl-dev libgnutls28-dev xz-utils
          apt-get install -y git/buster-backports

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Nox
        run: |
          python -m pip install --upgrade pip
          pip install nox

      - name: Build Docs
        run: |
          nox --forcecolor -e docs

      - name: Store Generated Documentation
        uses: actions/upload-artifact@v2
        with:
          name: mayflower-html-docs
          path: docs/build/html

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
          if-no-files-found: error