name: Pre-Commit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Pre-Commit:
    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files
      pull-requests: read  # for dorny/paths-filter to read pull requests
    name: Run Pre-Commit Against mayflower

    runs-on: ubuntu-latest

    container:
      image: python:3.8.6-slim-buster

    steps:

    - name: Install System Deps
      run: |
        echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list
        apt-get update
        apt-get install -y enchant git gcc make zlib1g-dev libc-dev libffi-dev g++ libxml2 libxml2-dev libxslt-dev libcurl4-openssl-dev libssl-dev libgnutls28-dev
        apt-get install -y git/buster-backports

    - uses: actions/checkout@v2

    - name: Install Pre-Commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit install --install-hooks

    - id: changed-files
      name: Get Changed Files
      uses: dorny/paths-filter@v2
      with:
        token: ${{ github.token }}
        list-files: json
        filters: |
          repo:
            - added|modified:
              - '**'
          deleted:
            - deleted:
              - '**'

    - name: Check ALL Files On Branch
      if: github.event_name != 'pull_request'
      run: |
        pre-commit run --show-diff-on-failure --color=always --all-files

    - name: Check Changed Files On PR
      if: github.event_name == 'pull_request' && steps.changed-files.outputs.repo == 'true'
      run: |
        pre-commit run --show-diff-on-failure --color=always --files ${{ join(fromJSON(steps.changed-files.outputs.repo_files), ' ') }}