name: Release

on:
  workflow_dispatch:
    inputs:
      kind:
        required: false
        type: string
        default: dev
      package_command:
        required: false
        type: string
        description: Command used to build python package
        default: >-
          python -m
          build
          --wheel
          --outdir dist/

permissions:
  contents: read

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
      pull-requests: read
    with:
      kind: "${{ inputs.kind }}"
      package_command: "${{ inputs.package_command }}"
