name: Build and Release

on:
  workflow_dispatch:
    inputs:
      kind:
        required: false
        type: string
        default: dev
      package_command:
        required: false
        type: string
        description: Command used to build python package
        default: >-
          python -m
          build
          --wheel
          --outdir dist/

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      kind: "${{ inputs.kind }}"
      package_command: "${{ inputs.package_command }}"
    secrets:
      SSHKEY: ${{ secrets.SSHKEY }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
