name: Toolchain ( Docker )

on:
  workflow_call:
    inputs:
      changed-files:
        required: true
        type: string
        description: JSON string containing information about changed files

jobs:

  build_toolchain:

    name: "${{ matrix.target }} on ${{ matrix.host }}"

    runs-on: ubuntu-22.04

    if: fromJSON(inputs.changed-files)['toolchain'] == 'true'

    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64
          - aarch64

    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Docker Commands
        id: docker_cmds
        with:
          arch: aarch64
          distro: ubuntu22.04

          install: |
            apt-get update
            apt-get install -y build-essential libtool-bin linux-headers-$(uname -r)
            apt-get install -y help2man python3-all flex bison texinfo unzip gawk libncurses-dev rsync

          run: |
            python3 -m mayflower toolchain build --arch=${{ matrix.target }}


      - name: Logs toolchain docker ${{ matrix.target }}
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.target }}-linux-gnu-toolchain-logs
          path: mayflower/_toolchain/build.log
          retention-days: 5
