name: Test

on:
  workflow_dispatch:
    branches:
      - test
    inputs:
      version:
        required: false
        type: string
        description: Version to author

#permissions:
#  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: cicd
    env:
      SSHKEY: ${{ secrets.SSHKEY }}
    steps:
      - name: Secret test
        run: |
          echo "${SSHKEY}" | wc
